image: ubuntu:22.04

trigger-build:
  only:
    - main
  script:
    - apt-get update && apt-get install unzip curl -y
    - bash build.bash
    - mv build public
  artifacts:
    paths:
      - public
